name: Elixir CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.3 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - run: sudo apt-get install sshpass
    
    - name: Setup enviroment variables
      run: echo ::set-env name=MIX_ENV::prod
    - run: echo ::set-env name=SECRET_KEY_BASE::${{ secrets.SECRET_KEY_BASE }}
    - name: Install Dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: NPM
      run: cd ./assets/ && npm install -S webpack && npm install
    - name: NPM deploy
      run: npm run deploy --prefix ./assets/
    - name: Phoenix Digest
      run: mix phx.digest
    - name: Phoenix Release
      run: mix release
    - run: rm -rf ./assets && rm ./deps/
    - name: Copy to server
      run: sshpass -p ${{ secrets.PASSWORD }} scp -P ${{ secrets.SSH_PORT }} ./ ${{ secrets.SSH_USER }}@${{ secrets.DEPLOY_HOST }}:app

